name: Verify Migrations

on:
  pull_request:
    branches:
      - main
    paths:
      - "migrations/**"
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: execute flyway in docker 🐳
        run: docker-compose up --abort-on-container-exit
