name: verify server load

on:
  push:

jobs:
  load_execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: start docker
        run: docker-compose up -d
      - name: Make Directory for results
        run: mkdir -p LoadTestResults
      - name: Start application
        run: |
          npm i --prefix ./server && (npm start --prefix ./server&) & sleep 10
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.44.0/k6-v0.44.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
      - name: Run k6 local test
        run: |
          ./k6 run test/load/index.js --vus 10 --duration 10s --out json=./LoadTestResults/loadOutput.json
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: LoadOutput
          path: ./LoadTestResults
